### ISSUE TITLE
TOML repair

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#100]
- [x] include fields from #31 in TOML template
- [x] document metadata in specification sheet
- [x] rename ontology (#99)
- [x] update TOML examples
- [ ] notify Alec

--

- [ ] implement production metadata (#68)

**Comment by moedn** [comment]
changelog:

- `outer-dimensions` and `dim-outer-dimensions` where merged to dimension specific versions, e.g. `outer-dimensions-mm`

**Comment by hoijui** [comment]
I think this can be closed too, right @moedn ?

**Comment by moedn** [comment]
jepp :) thanks for cleaning up!
