### ISSUE TITLE
Add `publication` to support ODRL-4

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#106]
Scientific publications may be also a confirmation of documentation completeness (since they are peer reviewed)

## for the TOML template

add

`publication` = [URL] (= some unambiguous reference, preferably a DOI)

## for the TTL/RDF sample

add 

`hasPublication` (ObjectProperty)
`Publication` (class)
`reference` (DataProperty of Publication)

**Comment by hoijui** [comment]
to look for fitting properties (for having linked data):
https://lov.linkeddata.es/dataset/lov/terms?q=publication

What makes most sense to me from what I found there, is from the nature.com ontology:

```turtle
@prefix npg: <http://ns.nature.com/terms/> .

npg:Publication
    a owl:Class ;
    rdfs:isDefinedBy <http://ns.nature.com/terms/> ;
    rdfs:subClassOf npg:Concept ;
    skos:definition "The :Publication class groups together all individuals (or part of) created as the result of the publishing process. Note that we are not referring here to the physical artefacts, but just their abstract counterparts."@en ;
    skos:prefLabel "Publication"@en .

npg:hasPublication
    a owl:ObjectProperty ;
    rdfs:domain npg:PublicationEvent ;
    rdfs:isDefinedBy <http://ns.nature.com/terms/> ;
    rdfs:range npg:Publication ;
    skos:definition "The :hasPublication property relates a publication-event to a publication."@en ;
    skos:prefLabel "Has Publication"@en .

npg:doi
    a owl:DatatypeProperty ;
    rdfs:domain npg:Publication ;
    rdfs:isDefinedBy <http://ns.nature.com/terms/> ;
    rdfs:range rdfs:Literal ;
    skos:definition "The :doi property specifies a DOI number for a publication."@en ;
    skos:prefLabel "DOI"@en .
```

**Comment by moedn** [comment]
alrighty; to make this applicable in the end, it still needs to be implemented into the krawler and the frontend; but at least the ontology supports it :)

**Comment by hoijui** [comment]
wow, excellent! :o
.. you got your RDF skills together! :-)
