### ISSUE TITLE
US or UK spelling in the standard?

### ISSUE THREAD

**Issue by hoijui** [OPEN-NEXT/OKH-LOSH#133]
Especially important for the properties in the actual technical specification,
e.g. `organization` vs `organisation`.

Is there some international standard/guideline for which to use?

For long-term historical reasons, one could assume it would be UK spelling,
but given that this is an IT standard,
and a huge part of modern IT standards originated in the US,
one could just as much assume this as the more fitting option.

**Comment by hoijui** [comment]
GitHub for example,
has `organizations`, not `organisations`.

_Alternative:_ Try to avoid words with differences altogether?

StackOverflow supposedly prescribes US spelling for its own tags:
https://meta.stackexchange.com/a/23873/384667

A more general and at the same time more fitting question about the topic on SO:
https://stackoverflow.com/questions/157807/gb-english-or-us-english \
**-> Use US spelling in code and tags and the like**

**Comment by moedn** [comment]
seems like en-US seems by far the most commonly used variant :) en-GB was only used because it's the standard language in EU projects, but for OKH-LOSH I'd be in favor for en-US

**Comment by hoijui** [comment]
**US** it is!
