### ISSUE TITLE
Documentation and Definitions of Open Documentation Readiness Levels (ODRL)

### ISSUE THREAD

**Issue by infinite-dao** [OPEN-NEXT/OKH-LOSH#139]
Hej-hej,

some definitions are off

1. the open documentation readiness levels (ODRL) 4 or 5 (?) — the code ODRL 4 but ascribes the label as being ODRL 5: https://github.com/OPEN-NEXT/OKH-LOSH/blob/7dacd64050d2495763741a9646fcdc49684f6fe9/OTRL.ttl#L147 <br/>https://github.com/OPEN-NEXT/OKH-LOSH/blob/7dacd64050d2495763741a9646fcdc49684f6fe9/OTRL.ttl#L150

2. the comment https://github.com/OPEN-NEXT/OKH-LOSH/blob/7dacd64050d2495763741a9646fcdc49684f6fe9/OTRL.ttl#L109 should it not describe ODRL instead of OTLR ?

**Comment by hoijui** [comment]
Thank you @infinite-dao ! :-)
It is now all fixed (and much more).

In general, it should now all be much more consistent, between the human docu and the machine-readable one, and what the krawler spits out.
