### ISSUE TITLE
include synonyms in ontology

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#42]
open section and define

- OKH terms 
- Open-O-Meter terms

as synonyms

**Comment by hoijui** [comment]
is there some special RDF/OWL "synonyms" mechanism?
.. or can you give an example what you are thinking of?

**Comment by moedn** [comment]
Not aware of any.
@addshore any suggestion how to have various names for the same property? This was a soft requirement from WP2

**Comment by addshore** [comment]
> I assume simply defining multiple `rdfs:label` for the same property would do it

Once mapped into Wikibase structures this sort of thing would eventually end up being exposed as:

Multiple primary labels in different languages:
```
rdfs:label "Some English Name"@en ;
rdfs:label "Some French Name"@fr ;
```
(also as skos:prefLabel and schema:name)

Additional labels in a language are then mapped to `skos:altLabel`

**Comment by moedn** [comment]
dismissed; we probably don't wanna mess up the ontology with loads of different vocabolaries here. synonyms can be stated in the rdfs:comment
