### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#57]
- Why Wikibase?
  - editable by both humans and machines
  - → OKHv2 enables now humans to work on the data basis directly, making Wikibase optional and the data set more resilient
  - reference to other Wikibase examples for frontend design (as https://linkedopendata.eu/wiki/The_EU_Knowledge_Graph)
  - visualise outside Wikibase (since Wikibase itself is just as a backend, pages or not customisable) e.g. [this page](https://wikidocumentaries-demo.wmflabs.org/)

**Comment by moedn** [comment]
see also references in #3 or rather #84

**Comment by moedn** [comment]
distributed database + crawler allows
- automatic updates (information hosted on the TUB observatory very quickly became outdated after the project ended)

**Comment by moedn** [comment]
From the xx

- start with the results, put approach & methodology in the annex; don't repeat project justification
- clearly point out (maybe in an extra section): what's new / added value

**Comment by hoijui** [comment]
wikibase is gone, reporting is done
