### ISSUE TITLE
replace development-stage by TLR

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#73]
widely used, extensively tested, includes everything we need

for further reasoning see https://en.wikipedia.org/wiki/Technology_readiness_level

- [x] update templates
- [x] update existent TOML files
- [x] update ontology
- [x] fix Ontolgy after latest MD (inlcuding ODRL)

**Comment by moedn** [comment]
is there any TLR ontology existent we can just link to?

**Comment by moedn** [comment]
haven't found anything. apparently applications implement the few elements directly an no one bothered to publish their onotlogy :)

So here are the definitions & assessment practices: http://gridlab-d.sourceforge.net/wiki/index.php/Technology_Readiness_Levels#GridLAB-D_TRL_Definitions

**Comment by moedn** [comment]
I used EU formulations and applied minor changes to the NASA descriptions to use them  for OSH

**Comment by moedn** [comment]
Fieldready's TRL (multiple layers)

- https://airtable.com/shr7qCXm4FX58L9C2/tbluSH5uk2DO0xEU5/viwk3YZr3F9Uj9Z17/recUBEdoDxSG3Nvzq/fld5y8EGlFWD7KOxW/attf5kdBAyPAjeaRG
- some more templates: https://airtable.com/shr7qCXm4FX58L9C2/tbluSH5uk2DO0xEU5/viwk3YZr3F9Uj9Z17

**Comment by hoijui** [comment]
done! :-)
