### ISSUE TITLE
use upstream RDF fields

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#78]
e.g. instead of redefining `okh:spdxLicense` we could directly use `spdxt:ListedLicense`

- RDF spirit, yeah!
- only self-defined fields will remain

@hoijui how would I define `rdfs:domain` and other constraints like `owl:cardinality` then? Or is this not needed anymore?

**Comment by hoijui** [comment]
you either create a subProperty and overwrite/(re-)define `rdfs:domain` and co., or you use as-is. both are not possible.
what *is* possible:
if `spdxt:ListedLicense` defines `spdxt:LicencableObject` as its `domain`, then we could make our objects "implement" that (== make them a subClassOf that class).
