### ISSUE TITLE
define minimum criteria for importing WiF projects

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#79]
In order to avoid WIP, spam, advertising […] getting labelled as OSH, we define the necessary minimum for projects to get imported into WIF as the following:

- has a `name`
- has an `image`
- has a `licensor` (project owner)
- has a `license`
- has a `README`
- has ≥ 1 additional file

**Comment by moedn** [comment]
@ahane ↑ makes sense from your perspective?

**Comment by penyuan** [comment]
As you know I've been interacting with the WIF API for a while. AFAIK there is currently no clear indication of `licensor` (there's only the equivalent of "owner" but that's not explicitly `licensor`) and the `license` is not SPDX-compliant not to mention there are inconsistencies. For example, the `CC0` license returned from the API has a "license name" of CC BY (or something like that), and the CERN licenses don't include 2.0. I can double check specifics but just FYI.

**Comment by moedn** [comment]
thanks @penyuan ! indeed valuable information; if you can, please share some details about the `CC0` / `CC-BY` issue so I can file an issue for WIF

my perspective:

- `owner` = `licensor` (I know that's not true in all cases, but at least for 99% on WIF)
- the `license` string entry is checked against the SPDX list (as we need to do so for OKHv1 anyway)
- `CC0` returning `CC-BY` can be filed as a bug to WIF's dev team :)

**Comment by penyuan** [comment]
OK, let me get some more details, please stand by while I check my code.

However, I didn't know that WIF has a bug tracker??? Sorry if I got ahead of myself but does `WIF == Wikifactory`? Just want to make sure we're talking about the same thing. 😅

**Comment by ahane** [comment]
from my perspective this makes sense.
maybe the image requirement is a bit over-restrictive, as in the end the design files are what matters?

and yes @penyuan WIF == wikifactory!

**Comment by moedn** [comment]
@penyuan sorry for the misleading formulation; as far as I know wikifactory does not have any official bug tracker. Instead I'd just send a mail to Max &/ Tom

@ahane true. The reasoning behind the image-requirement was to filter WIP. I'd suggest we try both and see what we get. More projects are always good, but we shouldn't have more than 5…10% useless results when someone searches our DB :)

**Comment by penyuan** [comment]
Sorry for my late response @moedn, understood!

The Wikifactory API returns several fields when you ask about a license, such as `abreviation` (which should probably be spelled "abbreviation"????), `name`, and `title`. The issue is that they are sometimes inconsistent and don't match a real-world license. Some examples of the GraphQL query responses: 

No distinction between the different BSD license variants: 
```
{
        "abreviation": "BSD-2-Clause",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/bsd-2-clause/",
        "name": "freeBSD",
        "title": "FreeBSD License"
}
```

CC BY 4.0 for `abreviation` but CC0 for `name`:
```
{
        "abreviation": "CC-BY-4.0",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/cc-by-4.0/",
        "name": "cc0",
        "title": "Creative Commons Attribution 4.0"
}
```

No version number: 
```
{
        "abreviation": "CERN OHL",
        "isHeader": false,
        "link": "http://www.ohwr.org/projects/cernohl/wiki",
        "name": "cernOHL",
        "title": "CERN Open Hardware Licence"
}
```

Inconsistent version number: 
```
{
        "abreviation": "CC-BY-SA-4.0",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/cc-by-sa-4.0/",
        "name": "ccbysa3",
        "title": "Creative Commons Attribution-ShareAlike 4.0"
}
```

Also, I don't think any of the fields give SPDX license strings which I think is important.

The Wikifactory API allows a GraphQL query for the full list of licenses they support, below is the full response. Note that the list is not very comprehensive and has the problems I mentioned: 

```
{
  "data": {
    "licenses": [
      {
        "abreviation": "Permissive",
        "isHeader": true,
        "link": "",
        "name": "permissive",
        "title": "Popular permissive licenses (modifications may be shared without open sourcing)"
      },
      {
        "abreviation": "CC-BY-4.0",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/cc-by-4.0/",
        "name": "cc0",
        "title": "Creative Commons Attribution 4.0"
      },
      {
        "abreviation": "CC0-1.0",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/cc0-1.0/",
        "name": "unlicense",
        "title": "Creative Commons Zero (Public Domain)"
      },
      {
        "abreviation": "MIT",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/mit/",
        "name": "mit",
        "title": "MIT License"
      },
      {
        "abreviation": "BSD-2-Clause",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/bsd-2-clause/",
        "name": "freeBSD",
        "title": "FreeBSD License"
      },
      {
        "abreviation": "Copy Left",
        "isHeader": true,
        "link": "",
        "name": "copyLeft",
        "title": "Popular copyleft licenses (derivatives must be licensed under same terms)"
      },
      {
        "abreviation": "CC-BY-SA-4.0",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/cc-by-sa-4.0/",
        "name": "ccbysa3",
        "title": "Creative Commons Attribution-ShareAlike 4.0"
      },
      {
        "abreviation": "GPL-3.0",
        "isHeader": false,
        "link": "http://choosealicense.com/licenses/gpl-3.0/",
        "name": "gnuGPL",
        "title": "GNU General Public License 3"
      },
      {
        "abreviation": "OHL",
        "isHeader": false,
        "link": "http://www.tapr.org/OHL",
        "name": "tapr",
        "title": "TAPR Open Hardware License"
      },
      {
        "abreviation": "CERN OHL",
        "isHeader": false,
        "link": "http://www.ohwr.org/projects/cernohl/wiki",
        "name": "cernOHL",
        "title": "CERN Open Hardware Licence"
      }
    ]
  }
}
```

**Comment by moedn** [comment]
**Decision** ↓

In order to qualify for LOSH, projects from WIF must come with


- an SPDX-compliant license

- a README

- at least 1 file apart from README, LICENSE and CONTRIBUTION in the repository

Furthermore it's useful, but optional to gather projects that have a license, that is non-complient with SPDX identifiers. The previous crawling already helped to find the 'bugs' in the system: Most of it will be fixed once the corrected license templates have been implemented by WIF. However, also for the future this is valuable output.
