### ISSUE TITLE
ontology feedback v1

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#81]
mainly on [okh-sample-OHLOOM.ttl](sample_data/okh-sample-OHLOOM.ttl)

see this file on pastebin: https://pastebin.com/bUecrBuU

comments are mostly from @ahane ← :heart: thousand thanks for the feedback!

**Comment by hoijui** [comment]
old issue, plus data (on pastebin) is not available anymore -> closing
