### ISSUE TITLE
Appropedia connection

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#82]
There is a small team of individuals reading through Appropedia articles and creating metadata for them.

They are using a fork of OKHv1:
- https://www.appropedia.org/Template:Infobox_project
- that's a list of manually curated projects so far (using those infoboxes)
  - https://www.appropedia.org/w/index.php?title=Special:WhatLinksHere/Template:Infobox_project&limit=500

A (hopefully fairly simple) script could extract the data from those infoboxes for the listed projects and either create YAML files following OKHv1 or translate them directly into the new OKHv2 format (using TOML).

**Comment by moedn** [comment]
@hoijui fancy that? :)

**Comment by hoijui** [comment]
I wrote Emilio to ask, and hope there is an other way to gather this data then to crawl the wiki HTML.
I also see that they store more data in the template then what is displayed, so this way we could not fetch all the data they have stored.

**Comment by moedn** [comment]
done here: https://github.com/OPEN-NEXT/LOSH-Appropedia-Scraper
