### ISSUE TITLE
Maker Survey for Production Metadata

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#85]
- [x] create blank MD file for input
  - let people write in this document (give them temporary write access) → so it's documented _by them_, eliminating another layer of possible misconceptions
- [x] invite people to sessions
  - Daniel, Ali (see [here](https://github.com/OPEN-NEXT/LOSH/issues/94#issuecomment-816638166))
  - Joost, Steven, Henk (see [here](https://github.com/OPEN-NEXT/LOSH/issues/94#issuecomment-821021580))
  - also ask Stykka and SODAQ
- [ ] sessions performed
- [ ] document smoothed out
- [ ] send document around to everyone again for final feedback
- [ ] confront document with TsDC → document differences

---

[Original]

In the proposal, makers were identified as a source for production (batch size 1). Alternative mechanisms for commercial manufacturers already exist, but do have their limitations when applied for the maker context. These metadata could serve for matchmaking

2 Rounds to get them:

1. collect technology fields & corresponding data fields 
2. validate usefulness of fields for covered fields of technology

For technology: which technologies can you manufacture? → get the most frequent answers (define threshold)

For data fields: provide draft (which may bias participants) or confront everyone with an empty sheet (which may cause incompleteness)?

**Comment by moedn** [comment]
@GoSFhg what do you think? :)

**Comment by GoSFhg** [comment]
That sounds good, but we need to talk to the Fablabs/Makerspaces once if they still want to be identified as source of production. Then we can roll with the plan!

**Comment by moedn** [comment]
all done; will be implemented shortly
