### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#99]
Since we're not developing LOSH here, but rather the metadata specification, we should name it accordingly

- [x] rename repo
- [x] fix all broken URLs (e.g. base URLs)
- [x] rename `OKHv2` wherever it appears, since it's not (yet) the official v2 and unclear if it ever will be

current suggestion: `OKH-LOSH` (instead of `OKHv2`)

**Comment by hoijui** [comment]
* [ ] indicate in the README, that this is defining a new version/proposal of OKH (generally just making sure, that one gets the idea that this is an OKH derivate/further development)

**Comment by moedn** [comment]
I saw that the whole README would need to be reworked, so I just added a new section for now. Maybe we can recycle things for the new LOSH-Website repo then
